version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: ivs_api
    restart: unless-stopped
    tty: true
    links:
      - db
    depends_on:
      - db
    entrypoint:
      - ./docker/php/entrypoint.sh
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html/
    networks:
      - app-network

  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html/
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  db:
    image: mysql:5.7.32
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ivs_assessment
      MYSQL_ROOT_PASSWORD: qwerty123
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./docker/mysql/init.sql:/data/application/init.sql
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local
