kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
apiVersion: v1
data:
  mapUsers: |
    - userarn: arn:aws:iam::294459726178:user/faiz
      username: faiz
      groups:
        - system:masters
