apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  labels:
    tier: backend
data:
  default.conf : |
    server {
        listen 80;
        listen [::]:80;

        server_name  localhost;
        server_tokens off;

        root "/var/www/html/public";
        index index.php index.html index.htm;

        charset utf-8;
        sendfile off;
        client_max_body_size 100m;

        location / {
        try_files $uri $uri/ /index.php$is_args$args;
        }

        location ~ \.php {
          try_files $uri /index.php =404;
          fastcgi_pass 127.0.0.1:9000;
          fastcgi_index index.php;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          include fastcgi_params;
        }
    }
